### ISSUE TITLE
Look for inconsistent recipes 

### ISSUE THREAD

**Issue by MrCheeze446** [Jiingy/Jineric-Mod#51] opened 2021-02-04 01:31 UTC
help me make a list of crafting recipes that are either duplicates (for some reason) or inconsistent because we're all blind

**Comment by Jiingy** [comment] 2021-02-09 09:34
I'll go through the current recipes but I'm almost certain the recipes are fine now albeit a few missing.

**Comment by Jiingy** [comment] 2021-02-09 09:41
Closing this issue as soon I will be going through making sure all crafting recipes are working as intended, and I never really plan on releasing the mod with broken recipes. It's far more useful to have issues that directly address specific crafting recipes that are not working as intended or duplicates.

For future reference this is probably something best just put on discord as this issue is more of a reminder if anything.

**Closed as completed by Jiingy** 2021-02-09 09:41 UTC
Labels: 🔁 status: todo, ⚙️ complexity: 1
